### ISSUE TITLE
Unable to insert tof_gestures_platform.h file

### ISSUE THREAD

**Issue by Ann125** [stm32duino/Proximity_Gesture#7] opened 2019-02-22 04:54 UTC
Hi all,
When I am trying to insert tof_gestures_platform.h file to the simple ranging program in eclipse it is unable to include that file. After inserting this file (project->properties->C/C++ General->Paths & Symbols->Include->Add), it still shows the error " tof_gestures_platform.h - No such file or directory.  But I have successfully included other .h files like tof_gestures.h , tof_gesture_DIRSWIPE.h and tof_motion .h files. Can anyone help me to understand why I get this error(unable to include tof_gestures_platform.h) and how to resolve it?

**Comment by cparata** [comment] 2019-02-27 15:02
Hi @Ann125 ,
unfortunately it is very difficult for us to reproduce your issue. We officially support only the Arduino IDE and we did not experience any issue with this library in several sketches where we used it. So, I suggest to check the path of the tof_gestures_platform.h file in your eclipse setup; maybe you have a wrong path there. I hope that it can help you to solve your issue.
Best Regards,
Carlo

**Comment by Ann125** [comment] 2019-02-28 04:21
Hi Carlo,
Thank you for your reply. It resolves my issue. The problem was due to the wrong path. I want to know whether this library supports system workbench (stm32 nucleo board).

**Comment by Ann125** [comment] 2019-02-28 05:21
Hi @cparata,
Thanks for your reply. It resolves my issue. It was due to wrong path.  Another error occurred which is due to undefined reference to a function: tof_gestures_detectDIRSWIPE_1( ) which is defined in the tof_gestures_DIRSWIPE_1.h file. I was successfully added this tof_gestures_DIRSIPE_1.h file in the project. But I don't know why this error occurred. Can anyone help me to solve this issue.

**Comment by cparata** [comment] 2019-02-28 07:52
Hi @Ann125  , 
I suggest you to give a look at the inclusion model used in the X_NUCLEO_53L1A1_Gesture_Swipe1.ino sketch in the X-NUCLEO-53L1A1 library. Basically, you just need to include <tof_gestures.h> and then <tof_gestures_SWIPE_1.h> and it should work. If you still experience some issues, I guess it is always due to path issues, because your compiler is not able to find the tof_gestures_DIRSIPE_1.h file.
Best Regards,
Carlo

**Comment by Ann125** [comment] 2019-02-28 08:53
Hi @cparata 
I am using eclipse System workbench for the programming of stm32 nucleo board instead of arduino board. The example code X_NUCLEO_53L1A1_Gesture_Swipe1.ino can be used with arduino board. So I want to know whether it is possible to use these files (tof_gestures.h and tof_gestures_DIRSWIPE_1.h) in system workbench? If it is possible how can I solve this undefined reference function issue. 
After adding the tof_gestures_DIRSWIPE_1.h file, when I open declaration of the function 
tof_gestures_detectDIRSWIPE_1( )in the main.c file, it will automatically goes to the  tof_gestures_DIRSWIPE_1.h file. But it still shows the undefined reference to the function error. Can you suggest any method to solve this issue.
Thanks
Ann

**Comment by cparata** [comment] 2019-02-28 09:11
Hi @Ann125 ,
are you programming in System Workbench with X-Cube code? If so, maybe the issue can be due to the mixture of C and C++ code. You can try to rename the .cpp files of the library into .c files and see if in this way the error disappears. The library is platform independent, so it should work also on System Workbench.
Best Regards,
Carlo

**Comment by Ann125** [comment] 2019-02-28 10:28
Hi @cparata 
I am programming nucleo board in System Wokbench with X-Cube code. I have already named the .cpp files as .c file. But the error didn't gone. What will be the reason for this error?
Thanks & regards
Ann

**Comment by cparata** [comment] 2019-02-28 11:09
Hi @Ann125 ,
Unfortunately it is very difficult for me to reproduce this issue; in my opinion, it is due to some wrong settings in your System Workbench project. Please, check if the library folder is in the Includes path.
Best Regards,
Carlo

**Comment by Ann125** [comment] 2019-02-28 11:46
Hi @cparata ,
I have checked for the library folder in the includes path and it is found there. Can't find any wrong settings in my system workbench. Anyway thanks for your reply. 
Regards 
Ann

**Comment by cparata** [comment] 2019-02-28 14:09
Hi @Ann125 ,
the only possibility is that you share with us your project, so I can give a try with System Workbench and see if there is something wrong. Otherwise, it is impossible for me to help you.
Best Regards,
Carlo

**Comment by Ann125** [comment] 2019-03-01 06:35
Hi @cparata ,
Sure. But I am unable to upload my project files here. Could you tell me how to upload my eclipse files.


Thanks & regards
Ann

**Comment by cparata** [comment] 2019-03-01 07:51
Hi @Ann125 ,
you could put it in github in a fork of the Proximity_Library.
Best Regards,
Carlo

**Comment by Ann125** [comment] 2019-03-01 08:52
Hi @cparata,
I have uploaded my project file in a fork of Proximity_Gesture Library.  Please check and give suggestions about how to solve my error.
Thanks & Regards 
Ann
https://github.com/Ann125/Proximity_Gesture/raw/9897474784994e5ae81a97fab3d55b64b9ee8074/SimpleRanging.rar

**Comment by cparata** [comment] 2019-03-01 10:51
Hi @Ann125 ,
I gave a look to your code and I found a lot of mistakes in the usage of System Workbench (usage of absolute path instead of relative path, errors in the insertion of the files), so I suggest to learn better the usage of the tool (I know it is not so simple). Anyway, I updated the SimpleRanging example starting from the code that you can find in the X-CUBE-53L1A1 package, adding the files of the Proximity_Gesture library and it compiles well (you can find the modified code in the link below). So I will close this Issue because it is not valid anymore.
Best Regards,
Carlo

https://www75.zippyshare.com/v/fp5u6VXI/file.html

**Closed as completed** 2019-03-01 10:51 UTC
